### ISSUE TITLE
We should eslint the scripts

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-content#110]
`eslint` would probably have caught the mistake of creating a function called `package`. 
It would have avoided https://github.com/mdn/stumptown-content/issues/109

We shouldn't use `eslint` to worry itself about code formatting. We'll [use prettier](https://github.com/mdn/stumptown-content/pull/28) for that once the ADR settles.

**Comment by peterbe** [comment]
Acceptance criteria: That important eslint errors breaks the CI build.

**Comment by peterbe** [comment]
@joedarc Something you'd be interested in working on?

**Comment by peterbe** [comment]
Another thing it could notice also is unused imports. [Like this line](https://github.com/mdn/stumptown-content/blob/d3fb9fe9fe322508dbf6f7cf1ca5cc9afb6a6292/scripts/build-json/slice-prose.js#L1)

**Comment by joedarc** [comment]
@peterbe sure i can check this out 👍

**Comment by joedarc** [comment]
> eslint would probably have caught the mistake of creating a function called package.
It would have avoided #109

 55:16  error  Parsing error: The keyword 'package' is reserved 😄

**Comment by peterbe** [comment]
@joedarc Ever since I switched to create-react-app, I've never had to worry about `eslint`. I tried to enable it on stumptown-renderer but failed as it still complained about style formatting. I'm sure it's possible to get it right but I find it fiddly.
