### ISSUE TITLE
Can we flatten additional_prose?

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-content#118]
Spawned from this dicussion: https://github.com/mdn/stumptown-renderer/pull/89/files#r318050706

In that PR, the renderer deals very differently with `additional_prose` than it does with regular `prose`. In the packaged JSON the data struct is something like this:

```json
{
  "body": [
    {
      "type": "prose",
      "value": {
        "title": "Short description",
        "id": "short_description",
        "content": "<p>The <strong>HTML Video element</strong> ....</p>"
      }
    },
    {
      "type": "additional_prose",
      "value": [
        {
          "type": "prose",
          "value": {
            "title": "Styling with CSS",
            "content": "<p>Use the\n<a href=\"/en-US/docs/Web/CSS/list-style-image\">..."
          }
        }
      ]
    },
  ]
}
```

Why not just flatten that and manufacture an `id` so it becomes like:

```json
{
  "body": [
    {
      "type": "prose",
      "value": {
        "title": "Short description",
        "id": "short_description",
        "content": "<p>The <strong>HTML Video element</strong> ....</p>"
      }
    },
    {
      "type": "prose",
      "value": {
            "title": "Styling with CSS",
            "id": "styling_with_css",
            "content": "<p>Use the\n<a href=\"/en-US/docs/Web/CSS/list-style-image\">..."
        }
    },
  ]
}
```

**Comment by wbamberg** [comment]
In https://github.com/mdn/stumptown-content/pull/107 I wasn't sure whether to do this, but decided not to because `additional_prose` sections felt like a different kind of thing to the named prose sections. They don't have language-independent IDs in the way that `short_description` does. But yes, perhaps it would be better after all to treat them the same way.

**Comment by ddbeck** [comment]
Even if we have an `additional_prose` type that's different from `prose`, I think it still makes sense to flatten them (so if there are two additional prose sections, you get two `additional_prose`-type objects, instead of an object with an array of children).

**Comment by peterbe** [comment]
Flattening it would really help the renderer since then it'd be able to just loop over `document.body` straight up without needing a way to self-recurse. 
For example, I was hacking on the code that adds syntax highlighting to `document.body[x]` elements that are HTML and have `<pre><code>` tags in them.

**Comment by peterbe** [comment]
By the way, I'm very familiar with how the renderer worries about these. And there, I'm pretty sure it'd be fine if flattened. 
But if there's a good reason for keeping this nested, to make the React components simpler (avoiding a "more complex" recursion pattern), we can, in the renderer's `cli` rearrange the `document.body` to do the flattening there.
