### ISSUE TITLE
Migrate all HTML elements

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#128]
We've migrated 50 of the HTML elements. We need to migrate the remaining elements.

********

**Acceptance criteria:**

* All HTML elements are migrated. Note that this does not include HTML *input* elements.

**Comment by ddbeck** [comment]
Following the stumptown workweek, @wbamberg, @Elchi3, and I decided that we don't actually need or want to finish this task now. Our approach has changed a bit, with a focus on scraping to a less-detailed surface structure, to be written. Declaring this complete now.
