### ISSUE TITLE
Consider keeping element docs in the same directory

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#160]
At the moment HTML elements (and presumably in future all reference docs) each live in their own directory, e.g.

```
/elements
    /abbr
        /attributes
        /examples
        docs.md
    /audio
        /attributes
        /examples
        docs.md
...
```

We already have [an issue about giving these files meaningful names, rather than "docs.md"](https://github.com/mdn/stumptown-content/issues/93), and I think we should do that. I think we should also consider keeping them all in the same directory:

```
/elements
    abbr.md
    audio.md
...
```

**Reasons why we should do this:**
* it's much easier to work with than having 150 directories each containing one file. Much more compact.
* the current layout is inconsistent: guide pages don't get their own directories. This leads to some hacks and weirdnesses. For example: https://github.com/mdn/stumptown-content/blob/7ca36351a063bb0b9c2b2ad8eaf3f1ca63da6390/scripts/build-json/build-page-json.js#L51-L54
* other hacks and weirdnesses, for example: landing pages can use a `directory` directive, to say "include all items in this directory". But for reference items it's really interpreted as "include all items in directories under this directory", to enable a directive like "content/html/reference/elements" to actually work.

**Reasons why we shouldn't do this:**

The reason we don't do this is that these files want to point to subsidiary files, for "examples" and "attributes", and we would like to keep these subsidiary files close to the "main" file. So if you're working on, say, the `<audio>` element, then all the relevant docs are together.

So we could corral examples and attributes into a shared directory, like this:

```
/elements
    /attributes
    /examples
    abbr.md
    audio.md
...
```

...but that moves them further away from the "main" file. On balance though I think this might be better. But I'm not sure, and I don't know if there are alternatives I haven't thought of.

@ddbeck , @Elchi3 , as usual I would love to hear opinions.

**Comment by peterbe** [comment]
Not really an opinion but... What happens if I `cd` into `/elements/examples`. 
I noticed that `abbr` currently has 4 examples: https://github.com/mdn/stumptown-content/tree/master/content/html/reference/elements/abbr/examples

I think it kinda works because their names are hopefully unique in that the `abbr.md` front-matter  would list their explicit names. But doesn't it mean that you can't have an example called "simple" or "basic" or something because you don't know which `../*.md` file that belongs to.

Pretty soon we might have images too. If we have
```
/elements
    /attributes
    /examples
    /images
    abbr.md
    audio.md
...
```
then, you won't be able to call an image something like `screenshot.png`. But that would be a perfectly "sane" name if it was located inside `/elements/abbr/`.

**Comment by wbamberg** [comment]
Yes, true. It has its own set of problems. I'm just not sure which are worse. Definitely keeping "the examples for audio" close to "the main docs for audio" is a strong argument for the current setup.

One thing, though, is that we should probably treat guides and reference pages in the same way. After all, guides have examples too (and images). So I don't know now why I started treating them differently. Landing pages probably don't have examples, but might have images. I think I might feel happier about this directory-per-page thing if it was consistent across all things-that-map-to-pages.

**Comment by ddbeck** [comment]
> I think I might feel happier about this directory-per-page thing if it was consistent across all things-that-map-to-pages.

Yeah, reading your initial issue, this was my thought, too. I like the idea of having all the parts of a page in one place: I open a directory and I get everything I need (apart from any shared assets or examples, which hopefully will live in some obvious place too). But I _really_ like the idea of avoiding surprises.

If we were to have an exception to a folder-per-page structure, I think it would be for pages which have no other dependencies. If a Markdown file alone can generate a whole page, then it might make sense to not have a whole folder for it (but I'd also expect that we would lint and complain for standalone Markdown pages that attempt to use images, examples, or other assets).

**Comment by peterbe** [comment]
If it's something I feel strongly about, is that when you make a **code projects**, you're much better off with ...
```
/root 
  /dashboard
    tests
    images
    model
    view
  /aboutus
    tests
    images
    model
    view
```
...than...
```
/root 
  /tests
    dashboard
    aboutus
  /images
    dashboard
    aboutus
  /models
    dashboard
    aboutus
  /views  
    dashboard
    aboutus
```

I think someone else named it "Design for deletability" which is weird but perfect at the same time :)

**Comment by wbamberg** [comment]
Peter, I was wondering when you were going to make this point :). It is a good one though.

Thanks both for your thoughts on this. It really helps to be considered about these kinds of choices. It looks like we should go with directory-per-page, and make more of an effort to be consistent about this, especially with respect to guide pages. I'm working on migrating the guide pages for HTML at the moment, and will be making them live in their own directories.
