### ISSUE TITLE
BCD tables in guide pages

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#170]
I've been working on migrating all the HTML guides to stumptown, and one thing has come up that I think will block this work.

Guide pages consist of unstructured prose content, which can embed special content using directives. Currently we support only live samples using a directive called `embed-example`. But guide pages also want to embed browser compat tables sometimes. This is in general simple to add: we can have a new directive that can add a `browser_compatibility` item to the built JSON, and the renderer already knows how to render the tables.

But there's a catch. In reference docs, the `browser_compatibility` ingredient is not quite used to render a single BCD table, but to render *the "Browser compatibility" section of the document*. So the rendered output contains an H2 "Browser compatibility", followed by a single table.

But in guide pages, we really want to render just a single BCD table. For example, take https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_settings_attributes#Browser_compatibility. This wants to render two tables, with H3 headings for them. So it seems like the source should be something like:

```
## Browser compatibility

### <script crossorigin>

{{{{{embed-compat: path.to.script.crossorigin}}}}}

### <video crossorigin>

{{{{{embed-compat: path.to.video.crossorigin}}}}}
```

We can't do this with the current stumptown-renderer.

So it seems like maybe there are two things that might be able to appear in the built JSON:

* `browser_compatibility_section` (maybe) that renders a complete BCD section with an H2
* `browser_compatibility_table` (maybe) that renders just a single table

Of course the rendering code is 99% shared.

This is an analogous issue to https://github.com/mdn/stumptown-content/issues/150, where initially I thought we should try to adapt the existing `examples` ingredient to handle both contexts, but then thought we should treat them as distinct. The current resolution there is to have:

* `examples`, which is used in reference docs to describe complete "Examples" sections, and
* `example`, which is used in guide docs to embed a single example.

But perhaps `examples_section` and `example` might be better names? Or perhaps I'm on the wrong track here?

@peterbe , @ddbeck , @Elchi3 , opinions?

**Comment by Elchi3** [comment]
> In  reference docs, the `browser_compatibility` ingredient is not quite used to render a single BCD table, but to render _the "Browser compatibility" section of the document_.



>  But in guide pages, we really want to render just a single BCD table
> 
> ```
> ## Browser compatibility
> 
> ### <script crossorigin>
> 
> {{{{{embed-compat: path.to.script.crossorigin}}}}}
> 
> ### <video crossorigin>
> 
> {{{{{embed-compat: path.to.video.crossorigin}}}}}
> ```

I don't know much about stumptown-renderer yet unfortunately, so I'm not sure how the mechanics work. Would it possible to have it behave so that when we ask to render the `browser_compatibility` ingredient (from a reference recipe), it renders _the "Browser compatibility" section of the document_, and when we ask it to render via `{{{{{embed-compat: path.to.video.crossorigin}}}}}` it renders the single BCD table?

**Comment by peterbe** [comment]
Another possibly easier solution is to go from:
```json
    {
      "type": "browser_compatibility",
      "value": { MEAT }
    }
```

to:

```json
    {
      "type": "browser_compatibility",
      "value": [
         { "title": "<script crossorigin>", "content": { MEAT }},
         { "title": "<video crossorigin>", "content": { MEAT2 }}
       ]
    }
```

Then, all the BCD ingredient would need to do is something like this:

```diff
export class BrowserCompatibilityTable extends Component {
  ...
  render() {
-   const { data, category = "html" } = this.props;
+   let datas = this.props.data;
+   if (!Array.isArray(datas)) {
+       datas = [datas]
+  } 

    return <>
        <h2 id="Browser_compatibility">Browser Compatibility</h2>

-      <table className="bc-table bc-table-web"> ... </table>
+      {data.map(data => {  
+          return <React.Fragment key={something}>
+              {data.title && <h3>{data.title}</h3>}
+              <table className="bc-table bc-table-web"> ... </table>
+         </React.Fragment>
+          )}
+        
    </>
  }
```

PS. Saying "datas" makes me cringe a little but I'm trying to illustrate a point :)

**Comment by wbamberg** [comment]
@Elchi3 
>  Would it possible to have it behave so that when we ask to render the browser_compatibility ingredient (from a reference recipe), it renders the "Browser compatibility" section of the document, and when we ask it to render via {{{{{embed-compat: path.to.video.crossorigin}}}}} it renders the single BCD table?

No, the renderer doesn't know anything about page types or directives or anything like that. Which is I think a good thing.

@peterbe 
> Another possibly easier solution is...
(you said in chat you preferred your second solution)

The problem here is that because the renderer is rendering the supplied title as an H3, then it is is still making assumptions about the document structure, which it really can't do for guide pages.

For example, a guide might want to have a rendered output like:

```
<h2>Browser compat</h2>

    <h3>Some other H3<h3>

        <h4> This compat table title is an H4</h4>

            <div class="bc-table">...</div>

        <h4> This compat table title is also an H4</h4>

            <div class="bc-table">...</div>
```

As far as I can see there's no way for the guide page to express this.

For that matter, a guide page might also want to do:

```
<h2>Some other H2, not "Browser compatibility</h2>

    <div class="bc-table">...</div>
```

...and I don't see how the proposed renderer change can handle that either.

An alternative is that we do what I originally suggested in https://github.com/mdn/stumptown-content/issues/150: have stumptown-content supply the H2 title ("Examples" or "Browser compatibility") when it is wanted. If there is a title, the renderer renders it as an H2. If there is no title, the renderer just renders the bare content.

That's simpler, but less explicit, than having a separate `browser_compat_section` thing.

**Comment by peterbe** [comment]
> An alternative is that we do what I originally suggested in #150: have stumptown-content supply the H2 title ("Examples" or "Browser compatibility") when it is wanted.

First of all, Yes! I think this is a good idea. I.e. in the renderer's Examples ingredient it does something like this instead:
```diff
-export function Examples({ examples }) {
+export function Examples({ examples, title, id }) {
  return (
    <>
-     <h2>Examples</h2>
+     {title && <h2 id={id}>{title}</h2>}
      {examples.map((example, i) => (
        <Example key={i} example={example} />
      ))}
    </>
  );
}
```

**Comment by peterbe** [comment]
So generally, you're saying we must support both:
```
<h2>Browser compat</h2>

    <h3>Some other H3<h3>

        <h4> This compat table title is an H4</h4>

            <div class="bc-table">...</div>

        <h4> This compat table title is also an H4</h4>

            <div class="bc-table">...</div>
```
**and**
```
<h2>Browser compat</h2>

    <h3> This compat table title is an H3</h3>

        <div class="bc-table">...</div>

    <h3> This compat table title is also an H3</h3>

        <div class="bc-table">...</div>
```

Hmm...

**Comment by peterbe** [comment]
It feels like we're somewhat in agreement that the words "Browser Compatibilty", "Examples", "Compatibilité des navigateurs" shouldn't be hardcoded in the ingredient components in the renderer. Good. 

In general, you know the content best. If you need the full flexibility, make it so it can be an array of 1, array of multiple, array of arrays, array of arrays of arrays, arrays of arrays with titles etc. 
Once that's decided, and you know it can be done with `build-json` I think anything can be done inside the ingredient's render code. Don't hold back! I'm eager to help, in the renderer, once it's in packaged JSON.

**Comment by wbamberg** [comment]
> So generally, you're saying we must support both: [...]

Yes. But also things like:

```
<h2>My heading text</h2>

    <p>blah blah blah</p>

    <div class="bc-table">...</div>

    <p>blah blah</p>
```

etc.

> It feels like we're somewhat in agreement that the words "Browser Compatibilty", "Examples", "Compatibilité des navigateurs" shouldn't be hardcoded in the ingredient components in the renderer. Good.

I'm totally open to this, but I think it's a distraction at this point. Eventually we will need to decide this but we don't have to decide now. As far as the HTML experiment is concerned, both work. But what we have now *doesn't* work to render HTML guide pages.

So to summarise, I can think of two options:

* Option 1: make stumptown-content supply the title text as `title: "Browser compatibility"`, and make it optional.
    * If stumptown-content does supply `title`, the renderer renders it as H2, then renders the table
    * If stumptown-content does not supply `title`, the renderer just renders the table

This option is super-simple, but more implicit.

* Option 2: have 2 ingredients, like `browser_compatibility_section` and `browser_compatibility`.
    * `browser_compatibility_section` is rendered with an H2 "Browser compatibility" (either supplied by the content or the renderer, I don't mind) followed by the table
    * `browser_compatibility` is rendered as just the table.

This is more complicated, but more explicit.

**Comment by peterbe** [comment]
We did that for examples, didn't we? 
https://github.com/mdn/stumptown-renderer/commit/29c0b3c7b1aef6025ccfa69527618c21ded6a708#diff-5ed338e87fe3489890666b01728f047f

We'd export 2 components from `src/ingredients/browser-compatibility-table/index.js` and pick them accordingly when we loop through the sections. 

Let's do it! Shouldn't be hard.
