### ISSUE TITLE
Writer's guide says to use code style in headings but we recently decided to stop allowing that

### ISSUE THREAD

**Issue by a2sheppy** [mdn/stumptown-content#198]
We recently decided that we would no longer allow the use of `<code>` and other styes within headings in order to make headings less cluttered and to avoid issues with confusion doing links and the like. Are we reverting that decision for stumptown (and if so, why?), or is the use of `<code>` in headings such as in the "Values" section and elsewhere simply structural and not reflected in the resulting output when the end-user content is generated?

**Comment by wbamberg** [comment]
Are you just talking about attributes files? I can't think of anywhere else that uses code style. And yeah, I agree, there's no reason to use code style in headings in attributes files.

**Comment by a2sheppy** [comment]
Moved this to a comment on the PR. Closing.

**Comment by wbamberg** [comment]
I think we should probably make this change, so let's keep this one as a separate issue so we can track it.
