### ISSUE TITLE
Writer's guide: 

### ISSUE THREAD

**Issue by a2sheppy** [mdn/stumptown-content#199]
In the writer's guide, I see this, under the "examples" section:

> Note: this does not specify interactive examples, because we'd have to rewrite the live sample system if we wanted to do that.

This is confusing. Why does the live sample system's existence influence interactive examples? This could use clarification (I suspect there's an error in this sentence but I am not certain).

**Comment by ddbeck** [comment]
Hey Sheppy, is this (and #198) supposed to be a comment on #197?

**Comment by a2sheppy** [comment]
Sigh. Yeah. I had opened the file to read on Friday and when I got back
into it Monday I’d forgotten it was a PR I could comment on.

I’ll fix this after the kiddo is out the door. :)

-- 
Eric Shepherd
Senior Technical Writer, MDN Web Docs
https://developer.mozilla.org/
Blog: http://www bitstampede.com/

**Comment by a2sheppy** [comment]
This is now commented on the PR; closing.
