### ISSUE TITLE
Make JSON builder able to build more than one item

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#22]
From https://github.com/mdn/stumptown-experiment/pull/14#issuecomment-491050130

* Ability to use the cli to, by default, render ALL elements.
* Ability to render select few. E.g. node scripts/package/package.js video blockquote abbr to only build the HTML for those 3.

This will probably require us to fix a bunch of data that isn't currently formatted properly.

**Comment by peterbe** [comment]
To me, it would be more attractive to be able to pass *paths* to `build-json.js` rather a specific search string. 

At the moment, you can do `node scripts/build-json/build-json.js html/elements/` which will match
```
Processed: /Users/peterbe/dev/MOZILLA/MDN/stumptown-experiment/content/html/elements/abbr
Processed: /Users/peterbe/dev/MOZILLA/MDN/stumptown-experiment/content/html/elements/address
Processed: /Users/peterbe/dev/MOZILLA/MDN/stumptown-experiment/content/html/elements/article
Processed: /Users/peterbe/dev/MOZILLA/MDN/stumptown-experiment/content/html/elements/aside
Processed: /Users/peterbe/dev/MOZILLA/MDN/stumptown-experiment/content/html/elements/audio
Processed: /Users/peterbe/dev/MOZILLA/MDN/stumptown-experiment/content/html/elements/b
Processed: /Users/peterbe/dev/MOZILLA/MDN/stumptown-experiment/content/html/elements/base
...
```

or even this:
```
▶ node scripts/build-json/build-json.js html/elements/ca
Processed: /Users/peterbe/dev/MOZILLA/MDN/stumptown-experiment/content/html/elements/canvas
Processed: /Users/peterbe/dev/MOZILLA/MDN/stumptown-experiment/content/html/elements/caption
```

What I'd rather do is pass in the location of the directories. Then I can tab complete to like this:
```
▶ node scripts/build-json/build-json.js content/html/elements/c[TAB]
canvas/    caption/   cite/      code/      col/       colgroup/
```

**Comment by wbamberg** [comment]
I think this is done.
