### ISSUE TITLE
More compact format for examples

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#242]
Currently examples each live in their own directory, that contains:
* a "description.md" optionally containing some prose description plus front matter
* a separate file for each .js, .css, .html piece

For many examples this results in a lot of files, many of which contain a line or two. We talked in London about changing to a more compact format, like:

* one MD file per example, containing:
    * front matter
    * a prose section
    * one fenced code section for each language piece (plus perhaps one for hidden pieces)

e.g.

```
    ---
    title: Picking a color
    height: 317
    ---
    Let's look at a simple example, in which the user can choose a color. As the user adjusts the color, the border around the example changes to reflect the new color. After finishing up and picking the final color, the color picker's value is displayed.
    
    ```html
    <div id="box">
      <label for="colorPicker">Border color:</label>
      <input type="color" value="#8888ff" id="colorPicker">
      <p id="output"></p>
    </div>
    ```
    
    ```css hidden
    #box {
      width: 500px;
      height: 200px;
      border: 2px solid rgb(245, 220, 225);
      padding: 4px 6px;
      font: 16px "Lucida Grande", "Helvetica", "Arial", "sans-serif"
    }
    ```
    
    ```js
    let colorPicker = document.getElementById("colorPicker");
    let box = document.getElementById("box");
    let output = document.getElementById("output");
    
    box.style.borderColor = colorPicker.value;
    
    colorPicker.addEventListener("input", function(event) {
      box.style.borderColor = event.target.value;
    }, false);
    
    colorPicker.addEventListener("change", function(event) {
      output.innerText = "Color set to " + colorPicker.value + ".";
    }, false);
    ```
```

@Elchi3 , @ddbeck , thoughts?

********

## Acceptance criteria

Examples format is agreed and implemented, and all stumptown content is updated with the new format.

**Comment by peterbe** [comment]
I was curious how this'd look like in `code`.

Previewing...
<img width="924" alt="Screen Shot 2019-11-13 at 2 46 29 PM" src="https://user-images.githubusercontent.com/26739/68798451-7208f380-0624-11ea-92fe-81e891dd4227.png">

**Comment by peterbe** [comment]
And the extra ` hidden` doesn't seem to break here in GitHub commenting:
<img width="835" alt="Screen Shot 2019-11-13 at 2 48 59 PM" src="https://user-images.githubusercontent.com/26739/68798687-ce6c1300-0624-11ea-8e0b-803174f5e3d1.png">

**Comment by peterbe** [comment]
In other words... It looks great! 

But, it'd make it a bit harder to run something like:
```
prettier --write "content/**/examples/*.js"
```
but perhaps that preposterous since it's more likely that we execute some linter function via `unified` as per our current linter.

**Comment by wbamberg** [comment]
Yes, I was thinking of how nice this looks in an editor, but forgot to mention it, thanks for bringing it up. In general it makes things nicer for the humans, and a bit more difficult for the tools, as you say. But that seems like a good trade-off to make.

**Comment by peterbe** [comment]
Actually, suppose you wanted to have a rule like "All CSS examples should be Prettier formatted with the following configuration..."
Then, you'd want to apply that to examples as well as inline code snippets anyway.

**Comment by wbamberg** [comment]
While we are doing this we should also decide on a way to specify whether an example is a live example or not. At the moment this is done implicitly by providing a `height` property in the front matter, which is rather obscure.

The obvious suggestion is to have an extra front matter property like `example_type` that can be `live` or `static`.

I don't very much like this either though, because it introduces a hidden dependency between two apparently separate keys: if `example_type` is `live` then `height` must be given, otherwise it must be omitted. Also this doesn't help with `height` being obscure. So it might be better to have an optional `result` (or `output`, or `example_output`) property, that is given if you want the example to show the result of the sources, and that has a mandatory `height`:

```
---
title: Picking a color
result:
    height: 317
---
```

**Comment by Elchi3** [comment]
I like the compact format in one file and using (deep) structure to demarcate things.

> The obvious suggestion is to have an extra front matter property like example_type that can be live or static.

Yeah, not sure whether this is a good idea. On current MDN pages, we often even ask the user to pick *how* they want to play with the example code. Many other sites do this, too. That is, offer to see static code, offer to copy it to clipboard, offer to load it into a custom live sample environment, offer to run it codepen/jsfiddle/whatever. And this experience might differ depending if you look at CSS code or JS or a Web API thing. So, hard to tell at this point. I think, ideally, we store examples flexible enough, so that the render could decide how to actually present examples and provide exporting options to other services, etc.

Going with `result` and `height` seems fine with me for now. We need to learn about more examples to make a good call here later then, I think.

**Comment by ddbeck** [comment]
If static examples are going to be like live examples, except that the code blocks aren't rendered into the live output, maybe liveliness is a feature of the `html` code fence itself? Like this:

```markdown
      ---
      title: Some example
      ---

      Some explanatory text

      ```html live height=123px
      <div>…</div>
      ```
```

**Comment by wbamberg** [comment]
>> The obvious suggestion is to have an extra front matter property like example_type that can be live or static.
>
> Yeah, not sure whether this is a good idea. On current MDN pages, we often even ask the user to pick how they want to play with the example code. Many other sites do this, too. That is, offer to see static code, offer to copy it to clipboard, offer to load it into a custom live sample environment, offer to run it codepen/jsfiddle/whatever. And this experience might differ depending if you look at CSS code or JS or a Web API thing. So, hard to tell at this point. I think, ideally, we store examples flexible enough, so that the render could decide how to actually present examples and provide exporting options to other services, etc.

I don't understand how this is relevant though. Of course the renderer can choose how to present an example. For example, stumptown-content can be agnostic about whether it's shown as something like the existing live samples, or using an embedded CodePen. But the point of this property is to indicate that it is *possible* to render the example as live, because it is actually possible to execute it, and this is a thing that only the content knows, so it needs to tell the renderer.

> If static examples are going to be like live examples, except that the code blocks aren't rendered into the live output, maybe liveliness is a feature of the html code fence itself? Like this:

I think liveliness is a basic property of the whole example (not just the HTML block) and it's much more visible in the front matter.

**Comment by Elchi3** [comment]
> But the point of this property is to indicate that it is possible to render the example as live

I think I'm not 100% clear what makes an example live. Code snippets should usually be all executable, but I guess live means that they show or demo some meaningful output to play with, too? How do they then differentiate to interactive examples? Does live mean there is a (simple) "result" pane?

But actually, I agree and I think it might often be a content choice which rendering options we want to give to code examples and I think in a way interactive-examples have this, too. So, I think it makes sense if stumptown-content has an `options` key for examples, so that it could tell the renderer how to present example code.

```yaml 
title: fancy typedarray example 
options: 
  result-pane-type: interactive-js-console (could also be interactive-css, codepen-embed or what kinds of result panes we wish to support)
  result-pane-height: 200px
  codepen-link: https://codepen.io/ykob/pen/Bowqwr
  ...
```

**Comment by wbamberg** [comment]
> I think I'm not 100% clear what makes an example live. 

What makes a rendered example live is that the page shows the example code and shows the output of it alongside. (What makes an example interactive is that the user can edit the example code and see the results update.)

What makes an example "live-enabled" is that the code is executable, self-contained, and provides a tangible output, so the renderer can stuff all the code into an iframe and the user can see the result.

>  Code snippets should usually be all executable

For example, in https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon:

```js
window.addEventListener("unload", logData, false);

function logData() {
  navigator.sendBeacon("/log", analyticsData);
}
```

or in https://developer.mozilla.org/en-US/docs/Web/API/Window/vrdisplayfocus_event:

```js
window.addEventListener('vrdisplayfocus', function() {
  info.textContent = 'Display focused.';
  reportDisplays();
});
```

or all the examples for the `<audio>` element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#Examples.

> it makes sense if stumptown-content has an `options` key for examples, so that it could tell the renderer how to present example code.

I think of all the front matter as containing options, so it seems odd to have an `options` object as well (another way to put this: I don't think putting properties inside an `options` object at all affects the discussion about which properties we should have or how they should be related).

> title: fancy typedarray example 
options: 
      result-pane-type: interactive-js-console (could also be interactive-css, codepen-embed or what kinds of result panes we wish to support)
      result-pane-height: 200px
      codepen-link: https://codepen.io/ykob/pen/Bowqwr
  ...

It's hard to evaluate this because I'm not sure what all the meanings of the different `result-pane-type` values are and how the renderer is expected to support them. Is it suggested that the renderer should natively support interactive examples? Because that's a much bigger question. As for `codepen-embed`, as I said above I think stumptown-content ought to be agnostic about whether an example is presented in a codepen or in some other format. `codepen-embed` seems like a very renderer-y thing to say.

At this point I think we should split off discussion of this from the main part of this issue, which was to provide a more compact format for examples. The other thing was just to improve the current situation where we don't explicitly indicate to the renderer that an example can be made live. I would like to improve that, but would not really like to block this other work on a much more involved conversation.

**Comment by Elchi3** [comment]
Thanks for your explanations and thoughts, Will!

> At this point I think we should split off discussion of this from the main part of this issue, which was to provide a more compact format for examples

Yes, sorry about derailing this. As you said in London and in our last planning meeting, examples are a big topic and we seem to require a more involved discussion and architecture discussion. Not here, though.

As said above, going with `result` and `height` in the front matter seems fine with me for now to provide a more compact format for examples.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/stumptown-content/pull/284 .
