### ISSUE TITLE
Update JS landing pages to be stumptown-compatible

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#274]
There are 2 KS macros in the JavaScript docs that are used to build landing pages, `jsindex` and `ListSubPages`. They are used to build three landing pages:

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Properties_Index
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Methods_Index
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors

I think we would like to implement these pages as stumptown "landing pages", which are a page type that consists primarily of [lists of links](https://github.com/mdn/stumptown-content/blob/master/project-docs/stumptown-writers-guide.md#link_lists), with an introductory description.

In order to make these pages be scrapable as landing pages we'll need to modify them to be "stumptown compatible".

"stumptown compatible" is a bit theoretical at the moment, since we don't have the ability to scrape them. But we should understand how we could map from the KumaScript to the equivalent in stumptown.

I think replacing `jsindex` will be tricky because it uses page tags, and stumptown doesn't (yet) understand tags, and you can't (yet) use them in link lists. Or perhaps we don't think these pages are useful, and they should be retired?

## Acceptance criteria

The following Wiki pages are modified to be "stumptown compatible":

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Properties_Index
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Methods_Index
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors

**Comment by wbamberg** [comment]
For some background, here's a summary of the current state of landing page support in stumptown.

At the moment in stumptown:

* landing pages consist of a prose description and one or more link lists.
* each link list can be specified in one of three ways:
    * **a literal list of links**
    * **a reference to a "chapter list"**, which is a reusable list of links (see e.g. [a chapter list for a learning area module](https://github.com/mdn/stumptown-content/blob/master/content/en-US/learn/html/Introduction_to_HTML.yaml))
    * **a reference to a directory** containing pages to include.

For example, [here's a simple landing page for HTML](https://raw.githubusercontent.com/mdn/stumptown-content/master/content/en-US/html/HTML.md). It includes two link lists:
* the first uses a [chapter list that includes the pages for a learning area module](https://github.com/mdn/stumptown-content/blob/master/content/en-US/learn/html/Introduction_to_HTML.yaml)).
* the second asks for all the pages under "/content/en-US/html/reference/elements".

That's it. I do expect we will need to add more features, if/when we need them.

**Comment by wbamberg** [comment]
**https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors**

This seems like an easy one to map to stumptown landing pages. It consists of:

1. some text
2. a macro call like: `{{ListSubPages("/en-US/docs/Web/JavaScript/Reference/Errors")}}`
3. some more text

I think it would be OK to move the text at (3) into (1).

The macro call seems like it could map straight onto the third type of link list in the comment above: https://github.com/mdn/stumptown-content/issues/274#issuecomment-575408111. Note though that this only works if we keep the same directory structure in stumptown, and there are definitely some places we'd prefer not to do this (e.g. the CSS docs). We've not really talked about directory structure mapping yet in our discussions about the scraper.

**Comment by wbamberg** [comment]
**https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Properties_Index
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Methods_Index**

These pages are more problematic. They're built using a special macro, [`jsindex`](https://github.com/mdn/kumascript/blob/master/macros/jsindex.ejs), that's only used to build these two pages.

The macro calls are hard to replace with link lists as they currently exist, because they use tags to fetch all JS methods, or properties, rather than just fetching all pages in a given directory. We could (and probably eventually will) want to support tagging in stumptown, and will probably also want to extend link lists with something like this kind of feature. Even without supporting generalized tagging, we could imagine the ability to ask for a list of pages that use a particular recipe, which would be enough here.

But these pages create a customised presentation of the links, grouping them by the initial letter of the method name (not the page title) and giving them as a collection of `<ul>` elements rather than a `<dl>`. So using a normal stumptown link list would change the presentation a lot.

Actually I don't like these very "one-off" macros and pages. I think it adds a lot of complexity to the platform and makes the user experience more confusing because pages aren't consistent.

In this case I also wonder how useful these pages are. Is it a common use case to know the name of a method (without knowing the name of the object that defines it) and use this page to look it up? This page also has some seeming usability issues: because it elides the object that defines a method, we get many sections like:

*****
<img width="676" alt="Screen Shot 2020-01-20 at 4 15 54 PM" src="https://user-images.githubusercontent.com/432915/72765194-216fc280-3ba0-11ea-86a3-5faaf835a911.png">

******

...where it's a little hard to see which `slice()` I'm looking for. It seems like this page was conceived in a much simpler time :).

So if it were up to me I would just retire these pages, but maybe people with deeper knowledge of these docs would have something to add.

**Comment by Elchi3** [comment]
I agree to retire the method and property index pages. They are not worth it. I think it was an experiment at the time and nicely showed what is possible with macros, but only because things are possible they are not necessarily useful. :)

**Comment by wbamberg** [comment]
👍 

I've made those 2 pages redirect to https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference . I might do the same for other locales, then we can kill this macro.

**Comment by wbamberg** [comment]
I've redirected all those pages and removed `{{jsindex}}`. Assuming the resolution for the [Errors](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors) page discussed in https://github.com/mdn/stumptown-content/issues/274#issuecomment-576448761 is OK, then we can close this.

We do still need to consider how to represent the other JS landing pages, but they don't use any of these macros.
