### ISSUE TITLE
Merge recipes for javascript-expression, javascript-operator, javascript-statement?

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#295]
We currently have three recipes for relatively atomic parts of the JS language: [javascript-expression](https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-expression.yaml), [javascript-operator](https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-operator.yaml), [javascript-statement](https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-statement.yaml).

These recipes are all the same. It's fine for recipes to be the same, but it seems that these three categories - expression, operator, statement - don't cover all the different sorts of thing that our JS docs cover. And it's not always clear, looking at our docs, which category some of the pages should fall into.

All this makes it look like having separate categories (and recipes) for these sorts of thing is not helpful to readers or to writers, and we should consider collapsing them together into a single page type. Our current best idea of what to call this type is just "javacript-language-feature".

**Comment by ddbeck** [comment]
Fixed by #297
