### ISSUE TITLE
Syntax highlighting

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-content#31]
In https://github.com/mdn/stumptown-experiment/blob/master/content/html/elements/video/prose.md there's a block uses 
```
  ```html
   ...
```

In GitHub flavored Markdown this is automatically turned into 
```
&lt;<span class="pl-ent">video</span> <span class="pl-e">controls</span>&gt;
  &lt;<span class="pl-ent">source</span> <span class="pl-e">src</span>=<span class="pl-s"><span class="pl-pds">"</span>myVideo.mp4<span class="pl-pds">"</span></span> <span class="pl-e">type</span>=<span class="pl-s"><span class="pl-pds">"</span>video/mp4<span class="pl-pds">"</span></span>&gt;
  &lt;<span class="pl-ent">source</span> <span class="pl-e">src</span>=<span class="pl-s"><span class="pl-pds">"</span>myVideo.webm<span class="pl-pds">"</span></span> <span class="pl-e">type</span>=<span class="pl-s"><span class="pl-pds">"</span>video/webm<span class="pl-pds">"</span></span>&gt;
  &lt;<span class="pl-ent">p</span>&gt;Your browser doesn't support HTML5 video. Here is
     a &lt;<span class="pl-ent">a</span> <span class="pl-e">href</span>=<span class="pl-s"><span class="pl-pds">"</span>myVideo.mp4<span class="pl-pds">"</span></span>&gt;link to the video&lt;/<span class="pl-ent">a</span>&gt; instead.&lt;/<span class="pl-ent">p</span>&gt;
&lt;/<span class="pl-ent">video</span>&gt;
```

We need a solution to do the same inside `build-json.js` so that the snippet of HTML has this stuff too.

**Comment by wbamberg** [comment]
Yes. I think this is connected to https://github.com/mdn/sprints/issues/1505: there are several Markdown implementations that support syntax highlighting for fenced code blocks.

**Comment by peterbe** [comment]
Code in prose is probably best done with whatever markdown implementation we're using. But I haven't attempted to solve this because the [Markdown tooling work](https://github.com/mdn/sprints/issues/1505) was wild (to me). 

But however that's going to work it would be nice to be more connected to this in the rendering of examples. In particular for the CSS! For example, for the examples rendering component, we should ideally have that rendered out as HTML too and whatever tool we use for that, we should have the CSS in the renderer. 

We're currently rendering examples something like this:

```
function RenderSources({ sources }) {
  return (
    <>
      {sources.html && <h4>HTML</h4>}
      {sources.html && (
        <pre>
          <code>{sources.html}</code>
        </pre>
      )}
  ...
```
What would be better is

```
function RenderSources({ sources }) {
  return (
    <>
      {sources.html && <h4>HTML</h4>}
      {sources.html && (
        <pre dangerouslySetInnerHTML={{ __html: sources.html_rendered}} />
      )}
  ...
```

This can certainly be done, in the cli of the renderer. We have that piece of code that packages a `index.json` for every page. So it could easily do something like this:

```javascript
  const options = {
    document: JSON.parse(data)
  };
  setExamplesRenderedHTML(options.document);
  ...
```

This can be done with something like [Prism](https://prismjs.com/) and the renderer just makes sure all blocks of example snippets are turned into HTML. 

All the renderer needs to worry about then is to make sure the web pages have the CSS that Prism relies on.

**Comment by wbamberg** [comment]
@peterbe , can we close this now you're doing syntax highlighting in the renderer?

**Comment by peterbe** [comment]
Yup!
