### ISSUE TITLE
Write linter ingredient handler for data.info_box

### ISSUE THREAD

**Issue by ddbeck** [mdn/stumptown-content#332]
A follow up to #320

We need an ingredient handler for `data.info_box`. This seems sort of straight forward—look for a table in some particular location—but info boxes seem to vary significantly across page types. For example, CSS pages use `cssinfo` macros in a different place than JS pages use `js_property_attributes`.

I would expect whoever takes this on to do one of:

* make a plan for distinguishing different info boxes (if not actually implementing all of them)
* break info boxes into different domain-specific types (e.g., `data.js_info_box`)
* get it working for JS and kick the can down the road for other content areas

**Comment by Elchi3** [comment]
This is one of the top warnings right now:

---
99 warnings    javascript-property/data.info_box/handler-not-implemented

**Comment by wbamberg** [comment]
I wrote this in an email (April 9th, when we were sprint planning) but unfortunately forgot to update the other places:

> I've not included this in the spec and suggest we don't do data.info_box for now. It's a rather controversial topic that would take a lot of modelling work, and isn't needed for the JS docs to be "stumptown compatible" (scrapable) unless we want to structure that content.

Unless anyone objects I suggest we resolve this by removing `data.info_box` from the recipe.

**Comment by Elchi3** [comment]
Closing this then.
