### ISSUE TITLE
U - Write a linter ingredient handler for data.class_constructor

### ISSUE THREAD

**Issue by ddbeck** [mdn/stumptown-content#333]
A follow up to #320 

We need an ingredient handler for `data.class_constructor`.

Note that this is very similar to https://github.com/mdn/stumptown-content/issues/348, so should be implemented after that story so we can reuse the same logic.

## Acceptance criteria

The linter checks the correctness of the `data.class_constructor` ingredient in recipes that include it, according to the specification: https://github.com/mdn/stumptown-content/blob/master/project-docs/javascript-linter-spec.md .

**Comment by Elchi3** [comment]
To estimate possible error fall out here, this is the current warning count:

---
57 warnings    javascript-class/data.constructor/handler-not-implemented

**Comment by ddbeck** [comment]
I expect #421 to address this.

**Comment by wbamberg** [comment]
This should be fixed by https://github.com/mdn/stumptown-content/pull/421.
