### ISSUE TITLE
Repo needs a license before employees of other companies can contribute to it. 

### ISSUE THREAD

**Issue by jpmedley** [mdn/stumptown-content#362]
I suggest using CCO as the [browser compatibility database](https://github.com/mdn/browser-compat-data/blob/master/LICENSE). Using the same license as another repo eliminate a review step for employees of companies that want to contribute.

**Comment by ddbeck** [comment]
See also https://github.com/mdn/stumptown-content/pull/29#issuecomment-494831419. The consensus there was that we need to leave the markdown content as CC-BY-SA (same as the wiki, [excepting code samples which are CC0](https://developer.mozilla.org/en-US/docs/MDN/About#Code_samples_and_snippets)) and set everything else to CC0. It does need a PR though.

**Comment by peterbe** [comment]
[We're going to need to do the same thing with Yari](https://github.com/mdn/stumptown-renderer/issues/408)
