### ISSUE TITLE
U - Test ingredient and recipe linting

### ISSUE THREAD

**Issue by ddbeck** [mdn/stumptown-content#392]
As an editor of wiki content, I want to be able to verify and demonstrate linting behavior independently of the wiki itself (e.g., for debugging and CI). We should have a test suite for `scraper-ng` that doesn't rely on the wiki being available or live wiki pages being in a specific state.

## Acceptance criteria 

- [x] Implement one or more tests for `scraper-ng`
- [x] Add tests to CI

**Comment by wbamberg** [comment]
@ddbeck , I think we can close this now, can't we?

**Comment by ddbeck** [comment]
Yes, agreed!
