### ISSUE TITLE
U - Write recipes for CSS properties

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#396]
**Note**: this story was originally to:

(1) identify which distinct recipes we'd need to write for CSS
(2) write all identified recipes.

But I think it would be easier to follow if we have separate stories for each page type, so I have now done that:

* [CSS types](https://github.com/mdn/stumptown-content/issues/441)
* [CSS selectors](https://github.com/mdn/stumptown-content/issues/440)
* [CSS functions](https://github.com/mdn/stumptown-content/issues/439)
* [CSS at-rules](https://github.com/mdn/stumptown-content/issues/466)
* [CSS at-rule descriptors](https://github.com/mdn/stumptown-content/issues/467)

That leaves this story to cover CSS properties only.

# Acceptance Criteria 
- [x] recipes for CSS property pages are written and checked into stumptown-content
- [x] spec for how to lint with these recipes is written and checked into stumptown-content

**Comment by wbamberg** [comment]
In this comment I'll analyze which different types of pages we have in the CSS documentation.

We have 1001 pages under https://developer.mozilla.org/en-US/docs/Web/CSS, which you can find listed [here](https://wiki.developer.mozilla.org/en-US/docs/User:wbamberg/all-css-pages).

Because the CSS page hierarchy is mostly flat, and our tagging is a mess, it's not that simple to figure out which pages we have or what sorts of things they document.

Page titles seem to be the most reliable clue here. I've used the following rules:

* guides start with an uppercase letter
* types start with "<"
* at-rules start with "@"
* pseudoclasses and pseudoelements start with ":"
* properties and at-rule descriptors start with lowercase letter or "-", and don't end with "()"
* functions start with a lowercase letter and end with "()"

This gives us something like:
* 192 guides
* 135 pseudoclasses and pseudoelements
* 35 types
* 71 functions
* 13 at-rules

= 446, leaving 555 properties and at-rule descriptors. Of those I think we have:

* 420 non-prefixed properties
* 86 prefixed properties
* leaving 49 at-rule descriptors

This suggests we could have the following page types/recipes:

* `guides`
* `css-property`
* `css-selector` (including both pseudoclasses and pseudoelements)
* `css-type`
* `css-at-rule`
* `css-function`
* `css-at-rule-descriptor`

**Comment by chrisdavidmills** [comment]
Looks pretty good, @wbamberg . I can't immediately think of any major page types you've missed.

The only outlier that immediately sprints to mind is the custom properties ref page:

https://developer.mozilla.org/en-US/docs/Web/CSS/--*

This isn't exactly a property, but can probably be treated like one in terms of what recipe structure it should conform to.

**Comment by wbamberg** [comment]
I've looked at some CSS property pages and suggest we could have a recipe for CSS properties like this:

```yaml
data:
  - title
  - short_title?
  - mdn_url
body:
  - prose.short_description
  - data.interactive_example?
  - prose.syntax
  - prose.description?
  - prose.accessibility_concerns?
  - prose.*
  - data.technical_summary
  - data.examples
  - data.specifications
  - data.browser_compatibility
  - prose.see_also
```
######

Some things to say about this:

## 1) Opening sections

```yaml
  - prose.short_description
  - data.interactive_example?
  - prose.syntax
  - prose.description?
```
...this is consistent with the structure of many of the JS recipes, such as https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-method.yaml.

The `prose.syntax` section is mostly the existing "Syntax" section (e.g. https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/perspective#Syntax), but I'm proposing we move the "Formal syntax" bit to the `data.technical_summary` ingredient. That would enable us to treat "Syntax" as a plain prose section. 

The `prose.description` is new for CSS property pages, and would collect the prose that's currently placed right after the interactive example in pages like [`perspective`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/perspective). This will involve some rework in some pages.

## 2) Accessibility concerns

This recipe adds a new optional prose section "Accessibility concerns". I think that's pretty noncontroversial.

## 3) Technical summary

This recipe adds a new mandatory `data.technical_summary` ingredient. This is my attempt to grapple with the info boxes created by `{{CSSInfo}}` and the formal syntax added by `{{CSSSyntax}}`. These page elements are a bit problematic but I don't think we are ready to abandon them yet. Currently formal syntax usually lives in the "Syntax" section, and CSSInfo lives in the "Specifications" section. Keeping them there would mean we couldn't use the same `syntax` and `specifications` ingredients as for the JS docs (and other docs). Also I like the idea of these two items living in the same section, as they both contain very dry content.

The linter will look for `{{CSSInfo}}` and `{{CSSSyntax}}` calls to validate this ingredient.

I've placed this in the middle of the recipe because that helps us keep the start and end of the page consistent with other page types. I think the middle of the page is where custom content is more likely to live (and that's already acknowledged in the fact that we place `prose.*` there.

I'm not sure I like the name "Technical summary" very much though.

## 4) Final sections

Again the final sections:

```yaml
  - data.examples
  - data.specifications
  - data.browser_compatibility
  - prose.see_also
```
...are consistent with the recipe for the JS docs and probably many other docs too.

#####

Comments, welcome, @chrisdavidmills , @ddbeck , @Elchi3 ?

**Comment by chrisdavidmills** [comment]
Looks pretty good to me, @wbamberg. Nothing imediately jumps out from my mind as being a section of content that you've missed.

My immediate gut reaction is that "Technical summary" should go lower down as it's useful to less people that the rest of the content. But I also read your description of why you put it there, and, yeah, I guess that makes sense. The beginning and end of the pages are the hottest real estate really. 

In terms of what to call it, yeah, "Technical summary" is a bit wishy washy. In the CSS specs I believe these terms are called "Property definition" — see https://drafts.csswg.org/css-transforms-2/#propdef-perspective. Could we follow suit with that? It's more of a definition, in the same sense that an API interface's WebIDL is a definition. But I'm not sure if that would help our users or confuse them. I'm thinking that the small percentage of users that actually care about this information would be able to make sense of it.

I also had a gut feeling that examples should be a bit higher.

**Comment by Elchi3** [comment]
> I'm proposing we move the "Formal syntax" bit to the `data.technical_summary` ingredient. That would enable us to treat "Syntax" as a plain prose section.

This makes sense to me.

> The `prose.description` is new for CSS property pages, and would collect the prose that's currently placed right after the interactive example in pages like [`perspective`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/perspective). This will involve some rework in some pages.

Great to borrow from JS here. I think it is a good idea to attempt some consistency across the domains. 
Do you think this section (and thus the recipe) would be different for CSS property vs CSS **shorthand** property? I would expect the shorthand explanation to appear in `prose.description`, but maybe we want to give it its own section? (see [mdn background](https://developer.mozilla.org/en-US/docs/Web/CSS/background) and [css tricks background](https://css-tricks.com/almanac/properties/b/background/) "background is made up of eight other properties:")

> I'm not sure I like the name "Technical summary" very much though.

"Technical definitions"?

**Comment by ddbeck** [comment]
Sorry for the delayed feedback on this. I like the overall gist of the recipe and I don't have any issues with it.

But because bike shedding is fun, I tried to come up with some alternatives for the "technical summary" problem ("technical" being one of those words that makes me grouchy). Here's what I came up with:

If the info box and syntax is all we're allowing in that section, then how about we say so? Here are some variations on that (in order of my preference):

* Formal definition and syntax
* Formal syntax and definition
* Formal details
* Formal definitions

Another option I came up with is _Specification highlights_, thinking that it's sorta distilled specification content. "Highlights" might be overselling things, though. 😆

Finally, we could hang a lampshade on this whole thing and call the section, _Obligatory technical disclosures_.

**Comment by wbamberg** [comment]
> I also had a gut feeling that examples should be a bit higher.

If we want to do that we should do it across the board, for JS docs and Web APIs and everything. I don't think we should because I think the main prose sections should flow together, and unless you move examples right after interactive example, they will divide the main prose sections.

> Formal definition and syntax

I like this.

> Do you think this section (and thus the recipe) would be different for CSS property vs CSS shorthand property?

This is interesting. One option I thought of was to represent shorthand properties explicitly. So we could have an extra "css-shorthand-property" recipe, and give it an extra ingredient "data.constituent_properties" or something, and expect to render it as something like:

```
## Constituent properties

The border property is a shorthand for the following CSS properties:

* border-width
* border-style
* border-color
```

So I mean, rather than handle it by making an existing ingredient be different for this shorthand properties, handle it by adding a new ingredient for them. This has the advantage that it makes this important fact about shorthand properties be super-scannable (as well as very machine-readable, in a structured content world).

**Comment by Elchi3** [comment]
> So we could have an extra "css-shorthand-property" recipe, and give it an extra ingredient "data.constituent_properties" or something, and expect to render it as something like [...]

Yes, I like this plan!

**Comment by wbamberg** [comment]
## CSS Selectors (pseudoclasses and pseudoelements)

I think there are about 137 pages here. 71 are prefixed (40 moz, 14 ms, 17 webkit).

The unprefixed ones have a fairly consistent structure:

* short description
* static code example (see for example  [`::grammar-error`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/::grammar-error))
* optional more prose
* H2#Syntax
* H2#Allowable/permitted properties (optional)
* H2#Accessibility concerns (optional)
* H2#Examples
* H2#Specifications
* H2#Browser compatibility
* H2#See also

A few things worth considering:

### The static code example at the start

These pages don't have interactive examples, but generally have a static code block instead, in the same place. So options here are:

1. Don't structure/enforce this, but just treat the static code example as part of a prose H2#Description section.
2. Don't structure/enforce this, but just treat the static code example as part of a prose H2#Syntax section (if we treat that as prose rather than formal syntax, see below).
3. Invent a new ingredient that's a static code sample.

I think I'd favour (2).

### H2#Syntax

* This usually contains the formal syntax via a call to `{{csssyntax}}`, and only the formal syntax (i.e. no prose description of the syntax, no `{{cssinfo}}`. 

* Occasionally it does not use the formal syntax (e.g. [`::grammar-error`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/::grammar-error)).

* Occasionally it uses the formal syntax and a prose description (e.g. [`:dir`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:dir#Syntax) ).

* The formal syntax is almost always extremely simple (e.g. [`:active`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:active#Syntax)).

* When formal syntax is complex is seems to be always because it's referring to the `<complex-selector-list>` or `<relative-selector-list>` types, which it then expands (e.g. [`:has()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:has)).

In this case I think we should remove the `{{csssyntax}}` calls and just represent the syntax as prose. In cases like [`:active`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:active#Syntax) I don't think it adds anything, and in the complex cases like [`:has()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:has) the syntax seems totally opaque. It would be better to have a prose definition of what we mean by `<complex-selector-list>` - either a short description in place or a longer one that these pages can link to.

## H2#Allowable/permitted properties

This is not a particularly common section but it crops up a few times. I'm on the fence about whether we should define a named prose section for it, or let it be a custom prose section.

## Prefixed pages

More than half of these pages are for prefixed pseudoclasses and pseudoelements. These are in general much less consistent than the unprefixed ones. Many of them are missing BCD and other mandatory sections.

Some of them are no longer supported by anyone, and I think we should archive these. For the rest though I think we will have to add the missing information. Potentially that's quite a bit of work...

## Proposal

All that leaves us with a recipe that could look like:

```yaml
data:
  - title
  - short_title?
  - mdn_url
body:
  - prose.short_description
  - prose.syntax             // including static code sample
  - prose.description?
  - prose.permitted_properties?
  - prose.accessibility_concerns?
  - prose.*
  - data.examples
  - data.specifications
  - data.browser_compatibility
  - prose.see_also
```

**Comment by ddbeck** [comment]
Thanks, Will. This one looks pretty promising to me. Just a couple points I had thoughts on:

- `prose.syntax` (including a static code sample) seems suspiciously similar to `data.formal_definition_and_syntax` ingredient we agreed on for CSS properties. Are these things really different from each other? In particular, you decided against removing `{{csssyntax}}` for properties and it's not clear to me why they're ripe for removal in selector pages.
- `H2#Allowable/permitted properties`: I'm inclined to make these explicit ingredients. I worry that `prose.*` will become a junk drawer for half-standardized ingredients. If we can structure it, let's do it.

**Comment by wbamberg** [comment]
> Thanks, Will. This one looks pretty promising to me. Just a couple points I had thoughts on:
> 
> * `prose.syntax` (including a static code sample) seems suspiciously similar to `data.formal_definition_and_syntax` ingredient we agreed on for CSS properties. Are these things really different from each other? In particular, you decided against removing `{{csssyntax}}` for properties and it's not clear to me why they're ripe for removal in selector pages.
> 

To start with the last point: I think removing `{{csssyntax}}` makes more sense here than it does for property pages.

We could (and do) argue about whether formal syntax is useful to include in property pages, but there's no question that:

* specs for properties present "Value" syntax in a very consistent way: [`transform`](https://drafts.csswg.org/css-transforms/#transform-property), [`background-size`](https://drafts.csswg.org/css-backgrounds-3/#the-background-size), [`gap`](https://drafts.csswg.org/css-align-3/#propdef-gap). 

* the value is often complex in a way that's hard to express in prose, and is very variable from one property to another.

With selectors, most of the time the syntax is trivial: [`:active`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:active#Syntax), [`::placeholder`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/::placeholder#Syntax), [`:hover`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:hover#Syntax) and in these cases the spec doesn't elaborate syntax for each selector at all (e.g. [`:active`](https://drafts.csswg.org/selectors-4/#active-pseudo)). What value is formal syntax adding in these cases?

Sometimes, when the selector is given arguments, then the syntax is more complex ([`:dir()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:dir#Formal_syntax), [`:has()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:has#Syntax), [`:host()`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/:host()#Syntax). In cases like this the specification does provide a formal description of the syntax (e.g. [`:has()`](https://drafts.csswg.org/selectors-4/#relational). But in almost all these cases, as far as I can make out, the formal syntax describes some types of selectors (compound selectors, relative selectors, complex selectors) and I think it would be **much** more helpful in these cases to have some prose documentation (dry, but prose) describing what these selector types all are, and then pointing to this documentation from the prose syntax section for a particular pseudo-class. As it happens the spec already does this (https://drafts.csswg.org/selectors-4/#structure) and I think this is much more useful than repeating the formal syntax of `<complex-selector>` on every page. So we ought to provide good documentation of what the different selector types are, cribbed from the spec, then link to it.

(I would be very open to removing formal syntax from properties as well, but I do think this case is more debatable.)

> * `prose.syntax` (including a static code sample) seems suspiciously similar to `data.formal_definition_and_syntax` ingredient we agreed on for CSS properties. 

I think it is much more like the `prose.syntax` that we have already for the [javascript-method](https://github.com/mdn/stumptown-content/blob/master/recipes/javascript-method.yaml) recipes : basically, the thing we use when we have decided not to structure the syntax description.

******

But that aside, suppose we decided formal syntax was useful for selectors? How would we want to represent it in a recipe? Would we want something like `data.formal_syntax` that's an H2#Formal_syntax, whose contents is a `{{csssyntax}}` call? Would we worry that the underlying data here is essentially the same as part of the `data.formal_definition_and_syntax` ingredient that we've proposed for CSS properties? So would this lead to us wanting to break up `data.formal_definition_and_syntax` into two separate ingredients? And if we did *that*, would we then fret that our ingredients currently only map to H2 headings (so we don't really have a way to define `data.formal_syntax` except as a top-level heading? 

I think one thing we're coming up against here is a tension between:
* the "structured content" idea, which wants to say "these things have formal syntax data associated with them. How you represent them in the page is a problem for the renderer" and 
* the "lint HTML pages" idea, which is very concerned with how the HTML itself is organized.

Perhaps we might prefer, then, instead of `data.formal_definition_and_syntax`, to have:

* `data.formal_definition`: defined as H2#Formal_definition_and _syntax containing `{{CSSInfo}}`
* `data.formal_syntax`: defined as H2#Formal_definition_and _syntax containing `{{CSSSyntax}}`

...this is friendlier to "structured content" because the recipe representation doesn't tie these items together. But it means we lose our simplistic mapping from recipe names to headings.

**Comment by wbamberg** [comment]
>     * `H2#Allowable/permitted properties`: I'm inclined to make these explicit ingredients. I worry that `prose.*` will become a junk drawer for half-standardized ingredients. If we can structure it, let's do it.

Very good point! Thanks for keeping me honest!  :-P

That said: at the moment this doesn't appear very often in the pages. I'm not sure whether that means it should appear more often, or that we should not make it an explicit part of the recipe. But if we do, yes I agree with your point here.

**Comment by wbamberg** [comment]
I think this thread is likely to get out of hand, so I created separate issues for [CSS selectors](https://github.com/mdn/stumptown-content/issues/440) and [CSS functions](https://github.com/mdn/stumptown-content/issues/439), and intend to create separate pages for the other CSS pages as I get to them. 

I moved the four comments about CSS selectors into the CSS selectors issue, and deleted them from here.

**Comment by wbamberg** [comment]
I've filed https://github.com/mdn/stumptown-content/issues/441 for CSS types.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/stumptown-content/pull/454.
