### ISSUE TITLE
U - Write ingredient handler for `data.formal_definition_and_syntax`

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#426]
According to https://github.com/mdn/stumptown-content/issues/396 it look likely that we'll have a `data.formal_definition_and_syntax` ingredient for CSS properties. We'll need to be able to lint for this ingredient.

## Acceptance criteria

* the linter lints CSS pages for the `data.formal_definition_and_syntax` ingredient

**Comment by ddbeck** [comment]
This is superseded by #458 and #457. Though I'm not sure if it needs to be entered into this sprint or not.
