### ISSUE TITLE
U - Write recipe for CSS types

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#441]
This issue is split out of https://github.com/mdn/stumptown-content/issues/396, which wants us to write recipes for all the CSS reference documentation page types.

I thought to keep things a bit easier to follow it might make sense to have stories to track different CSS recipes. This one is for **CSS types**. 

# Acceptance Criteria 
- [ ] recipe for CSS types pages is written and checked into stumptown-content
- [ ] spec for how to lint with this recipe is written and checked into stumptown-content

**Comment by wbamberg** [comment]
# CSS types

I count 35 pages for CSS types.

They have a form more or less like:

Short description
Interactive example (optional)
H2 Syntax
H2 Accessibility considerations (optional)
H2 Examples
H2 Specifications
H2 Browser compatibility
H2 See also

## Syntax

The Syntax section does not use `{{csssyntax}}` in any pages. It does use formal syntax-style a little bit. In general though, this section is a free-for-all, with lots of different structures.

Some types list items in Syntax that should perhaps be broken out into separate function pages (e.g. [`basic-shape`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/basic-shape) and [`easing-function`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/easing-function)).

It would be nice to design something consistent here, but so far we've treated H2#Syntax as unstructured prose. That looks like a better decision for JS methods, which are usually consistently structured anyway, than it does for pages like these. But I'm still not sure it's worth rewriting all these sections at this point - that feels like another project.

One interesting thing: the [`blend-mode`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/blend-mode) page uses a series of live samples inside Syntax. I think we ought to have an interactive example that covers some of the choices, and live samples in the (currently nonexistent) "Examples" section. But this made me think: if we are still interested in stumptown-compatibility, then our linter ought to complain about things like `{{EmbedLiveSample}}` calls occurring anywhere except the "Examples" section.

## Browser compatibility

The `display-*` types (e.g. [`display-inside`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display-inside#Browser_compatibility)) have lots of BCD tables.

The [`custom-ident`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/custom-ident#Browser_compatibility) page has a BCD section but no table, and the following text:

> As this type is not a real type but a convenience type used to simplify the description of allowed values, there is no browser compatibility information as such.

I really don't want to make `data.browser_compatibility` optional, but if this comment is to be believed maybe we should accommodate BCD sections that indicate that there isn't a table, as we do in the "Specifications" section for non-standard items.

**Comment by wbamberg** [comment]
For reference, all the CSS types I found:

* [`angle-percentage`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/angle-percentage)
* [`angle`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/angle)
* [`basic-shape`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/basic-shape)
* [`blend-mode`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/blend-mode)
* [`color_value`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/color_value)
* [`custom-ident`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/custom-ident)
* [`dimension`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/dimension)
* [`display-box`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display-box)
* [`display-inside`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display-inside)
* [`display-internal`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display-internal)
* [`display-legacy`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display-legacy)
* [`display-listitem`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display-listitem)
* [`display-outside`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/display-outside)
* [`easing-function`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/easing-function)
* [`filter-function`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/filter-function)
* [`flex_value`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/flex_value)
* [`frequency-percentage`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/frequency-percentage)
* [`frequency`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/frequency)
* [`gradient`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/gradient)
* [`image`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/image)
* [`integer`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/integer)
* [`length-percentage`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/length-percentage)
* [`length`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/length)
* [`number`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/number)
* [`percentage`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/percentage)
* [`position_value`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/position_value)
* [`ratio`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/ratio)
* [`resolution`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/resolution)
* [`shape`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/shape)
* [`string`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/string)
* [`time-percentage`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/time-percentage)
* [`time`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/time)
* [`transform-function`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/transform-function)
* [`translation-value`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/translation-value)
* [`url`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/url)

**Comment by wbamberg** [comment]
I think the main question here is whether to include `data.browser_compatibility` for CSS types.

I'm pretty convinced that we should not do this, simply because it's pretty meaningless to talk about browser support for a type, when you can't actually do anything with a type outside its relation to a property. To put it in concrete terms, as a web developer I probably don't care about whether some abstract type `<basic-shape>` is supported in the browser, but I do care about whether I can use `<basic-shape>` as a value of, say, the `clip-path` property. That is, BCD should attach to properties (and selectors and at-rules), not to types.

This isn't just an abstract point. Let's look at [`<basic-shape>`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/basic-shape). Its BCD is like:

<img width="532" alt="Screen Shot 2020-06-24 at 10 30 00 PM" src="https://user-images.githubusercontent.com/432915/85660256-447c3200-b66a-11ea-8b41-ed3c38b9d0a9.png">

How can I apply this? Well, according to the docs `<basic-shape>` can be used as a value for three properties: `clip-path`, `shape-outside`, and `offset-path`.

* [`clip-path`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/clip-path) BCD:

<img width="542" alt="Screen Shot 2020-06-24 at 10 32 25 PM" src="https://user-images.githubusercontent.com/432915/85660563-9f158e00-b66a-11ea-90a3-b1b2804fea90.png">


So this duplicates the `<basic-shape>` data, and gives it a different value for Chrome.

* [`shape-outside`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/shape-outside) BCD:

<img width="542" alt="Screen Shot 2020-06-24 at 10 34 11 PM" src="https://user-images.githubusercontent.com/432915/85660763-dab05800-b66a-11ea-9e57-98fa33f6a158.png">

This doesn't mention `<basic-shape>` explicitly, but gives the property a later version number in Firefox. I would assume from this that if you can use `clip-path` at all then you can use `<basic-shape>` with it.

* [`offset-path`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/offset-path) BCD:

<img width="541" alt="Screen Shot 2020-06-24 at 10 38 08 PM" src="https://user-images.githubusercontent.com/432915/85661757-ee0ff300-b66b-11ea-96b2-daeb23348bbf.png">

This also doesn't mention `<basic-shape>` explicitly, and gives the property later version numbers. Again, I'd assume from this that if you can use `offset-path` at all then you can use `<basic-shape>` with it.

So it's really not clear what the standalone `<basic-shape>` BCD is doing here, except possibly misleading people. And this isn't particularly a problem of the data, it's just a consequence of how we're defining content structures.

The big problem though is that for types that are very widely used, we would need to duplicate a lot of compat data in all the properties that use it. For instance, every property that uses `<length>` would need its own copy of the [quite intricate BCD for it](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/length#Browser_compatibility). This just doesn't seem practical given the state of our tooling.

So maybe it would be better to sweep this under the carpet for now.

If we do want to keep BCD for types, then there are a few issues. Most of the pages currently do have BCD tables, with AFAICT three exceptions:
* [`custom-ident`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/custom-ident)
* [`filter-function`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/filter-function)
* [`translation-value`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/translation-value)

This seems fairly easy. I'd suggest:
* replacing `custom-ident` with a guide page in custom identifiers.
* adding some fairly bogus BCD to `filter-function`, based on the `filter` data (we already do something similar for some other types)
* removing `translation-value` - I think it is an obsolete term now

All the `<display-*>` pages contain multiple tables, which is a different and harder sort of problem. We could perhaps subsume their content in the `display` property page, but I'm not sure about that.

Thoughts @chrisdavidmills , @ddbeck , @Elchi3 ?

**Comment by chrisdavidmills** [comment]
I really think we should not include these, and sweep them under the carpet for now. I totally agree with your notion of it not making sense to have this data appearing in isolation, not attached to the properties where the type is actually used.

In terms of how we could deal with this in the future, I can't stop thinking about how we could design a general purpose mechanism of representing data that is used in multiple places, which could serve types, and mixins, etc.

Maybe it could look something liek this:

```
{
  "css": {
    "properties": {
      "clip-path": {
        "__compat": {
          ...
        },
        "animations": {
          ...
        },
        "includes": [
          "basic_shape": "css.types.basic-shape"
        ]

        ...
      }
    }
  }
}
```

?

So you'd have to keep the type data separate internally, but then you could include it in another BCD data structure.

In cases where the data does differ between basic implementation of a type, and it being supported in a particular property, you could still include it as above, but then also include the differing datas separatey in the property:

```
{
  "css": {
    "properties": {
      "clip-path": {
        "__compat": {
          ...
        },
        "animations": {
          ...
        },
        "basic_shape": {
          ...
        }
        "includes": [
          "basic_shape": "css.types.basic-shape"
        ]

        ...
      }
    }
  }
}
```

And then the system could automatically create a dropdown note in places where it differs to say something like

```
Support for <basic-shape> in clip-path

xx

<basic-shape> originally introduced

xxx
```

Or maybe that's not worth it, I dunno, but you get the general idea.

Anyway, this is a bit of a digression. Should I move this idea somewhere else?

**Comment by ddbeck** [comment]
On the BCD question, I agree that some pages won't have meaningful a compat section and we should be able to accommodate that. Changing the ingredient to allow some escape hatch text is pretty easy. We can do that, no problem. The trick is _not_ using that escape hatch on pages where it's the only place where some compatibility information is made visible on MDN, because we haven't fixed the problem in BCD itself.

The problem of abstract data _in BCD_ is one we can deal with, but BCD has its own processes and contribution culture. Changing the schema is an option, but it's a hard one in some respects. I think it's possible to make this data show up in multiple places in a way that's transparent to BCD's consumers (which would spare us having to change the pre-Yari compat macro), but even that it is going to take a little time.

I think this suggests an approach like this:

1. Allow the escape hatch in the ingredient (but use it only in the cases where we do not have the data presently)
2. Change BCD to allow the practical concretization of abstract features
2. Start a sort of parallel track to "fixing page errors" that is "concretize abstract CSS features in BCD and escape hatch the affected pages"

The latter two steps probably deserves its own epic.

**Comment by wbamberg** [comment]
> On the BCD question, I agree that some pages won't have meaningful a compat section and we should be able to accommodate that. 

I don't think the issue here is this exactly. As I said upthread, there are only three pages currently missing BCD sections in this group, and I think we can fix these one way or another without an escape hatch. It's more that, in general, I don't think it makes much sense for this type of item to have BCD at all. So I don't think an escape hatch is the right way to support this - the right way is to omit the ingredient for this page type.

But anyway, it seems we're agreed that removing BCD from these pages is contingent on some other tooling that we don't want to block on, so the outcome is: include `data.browser_compatibility` in this recipe.

**Comment by wbamberg** [comment]
Fixed by https://github.com/mdn/stumptown-content/pull/496.
