### ISSUE TITLE
Constructor description linting bites back

### ISSUE THREAD

**Issue by Elchi3** [mdn/stumptown-content#459]
Someone edited the docs to not use our standard wording for constructors and I actually think they are correct in this case. So, I think we should not make our life hard and remove this linting. It is too strict. It was an interesting idea and I'm glad we tested it, but on a second look I don't think it is practical to lint on sentence / word level.

Thoughts?

```
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
1:1-1:1  error    Constructor description must end first sentence with ' object.'  javascript-class/data.constructor/constructor-description-third-node  html-require-ingredient
```

**Comment by ddbeck** [comment]
Do we have any other examples where this permissiveness could be useful? I'm reluctant to discard all the linting here (e.g., requiring `Creates a new <code>something</code>` might be good enough). Or we could be deliberately permissive to this particular form (`Create a new <code>something</code> value.`)

**Comment by wbamberg** [comment]
>  I actually think they are correct in this case

Can you elaborate on why this is better? Why is it better here and not for say [`String`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Constructor) or [`Number`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#Constructor) or [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Constructor)?

**Comment by Elchi3** [comment]
> Can you elaborate on why this is better? Why is it better here and not for say [`String`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#Constructor) or [`Number`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number#Constructor) or [Date](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Constructor)?

It is a bit weird, but `new BigInt()` throws, so I believe the idea is that there isn't a BigInt wrapper object, but only a bigInt value which you can get via the `BigInt('123')` or the literal `'123n'`.


> Do we have any other examples where this permissiveness could be useful?

https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol#Constructor is a similar case where I think we got a bit creative and used a wording to work around the linter.

So, I don't know. Maybe rewrite like we did for symbol? Which of these two is more useful to the reader?

**Comment by wbamberg** [comment]
> the idea is that there isn't a BigInt wrapper object, but only a bigInt value which you can get via the BigInt('123') or the literal '123n'.

OK. Like:

```js
let a = 1n;
let b = BigInt(1n);
// let c = new BigInt(1n); throws

console.log(typeof(a)); // bigint
console.log(typeof(b)); // bigint

let d = "hello";
let e = String("hello");
let f = new String("hello");

console.log(typeof(d)); // string
console.log(typeof(e)); // string
console.log(typeof(f)); // object
```

weird.

> new BigInt() throws

It throws with "BigInt is not a constructor" (in both Firefox and Chrome) which makes me think it is unhelpful of us to document it in a page titled "BigInt() constructor", linked from a section headed "Constructor". On the other hand the [spec also calls it a constructor](https://tc39.es/ecma262/#sec-bigint-constructor), so ¯\\_(ツ)_/¯.

> Which of these two is more useful to the reader?

Now you have explained it to me, I agree that "object" is likely to be misleading and "value" is better.


So we should tolerate that. I think I like Daniel's suggestion that we tolerate either "object" or "value", and see how that works out.

**Comment by Elchi3** [comment]
> It throws with "BigInt is not a constructor" (in both Firefox and Chrome) which makes me think it is unhelpful of us to document it in a page titled "BigInt() constructor", linked from a section headed "Constructor". On the other hand the [spec also calls it a constructor](https://tc39.es/ecma262/#sec-bigint-constructor), so ¯\_(ツ)_/¯.

Right, this is the core of the problem. I don't think documentation always needs to follow the specifications as close as possible, but I guess in spec terms it still is a constructor.

> So we should tolerate that. I think I like Daniel's suggestion that we tolerate either "object" or "value", and see how that works out.

Ok, that makes sense to me, too.

**Comment by ddbeck** [comment]
> the [spec also calls it a constructor](https://tc39.es/ecma262/#sec-bigint-constructor)

Reading up on it is sort of fascinating: https://github.com/tc39/proposal-bigint/issues/13. I guess it was _designed_ to be confusing, to make doing something inadvisable difficult (instead of, say, specifying that `new BigInt()` throws a helpful exception).

**Comment by wbamberg** [comment]
That's a really interesting thread Daniel, and helped me understand this corner of JavaScript much better. I think making the linter a bit more liberal here makes sense, but that thread also makes me think we could do with much more explicit guidance in general about the question of using constructors with primitive types. For example, if it's true that:

> users should never use new with a Number object tho, because it's widely considered a very bad practice to ever use boxed primitives

...then we should probably mention this in the [`Number()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/Number) page. I'll file an issue for this.

For now though I've filed https://github.com/mdn/stumptown-content/pull/463 for the linter.

**Comment by wbamberg** [comment]
Now https://github.com/mdn/stumptown-content/pull/463 is merged this page no longer produces an error.
