### ISSUE TITLE
The linter spec for data.constituent_properties can't handle the `all` property

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#526]
In the course of https://github.com/mdn/sprints/issues/3323, Chris hit a snag: the CSS [`all`](https://wiki.developer.mozilla.org/en-US/docs/Web/CSS/all) property is a shorthand for all properties with a few exceptions.

It doesn't seem at all desirable to list all properties here. The best solution I can think of is to add another allowable form to the [linter spec](https://github.com/mdn/stumptown-content/blob/master/project-docs/linter-spec.md#dataconstituent_properties):

> "This property is a shorthand all CSS properties, with the exception of:"

I don't love this since it's very clearly a workaround for a single page, but it's not too bad.

Thoughts, @ddbeck / @chrisdavidmills ?

**Comment by ddbeck** [comment]
In general, I'm fine with making explicit workarounds for specific pages. The recipes and linter spec should be a tool, not an anchor. It's making exceptions routine, not the exceptions themselves, that smells off to me.

For this page, I wonder whether we want to have a constituent properties section at all? A one-off recipe without it would be easy to implement and would not implicate the linter spec.

If we do want it, then I'm happy with this proposed exceptional text. For the record though, in a structured Markdown world, I'd expect an absurdly long frontmatter with a list of all the constituent properties and some special-case code that produces the aforementioned text.

**Comment by wbamberg** [comment]
I'm not keen on having a special recipe just for this. I'd prefer to pretend this isn't a shorthand property at all, and that might be better actually.

Especially given:

> in a structured Markdown world

I hadn't thought of this. You are right of course, and that means the special-case code and special-case metadata saying this page is special, just for one page.

So I think it would be better all round to call `all` a normal property, and describe its behavior in the prose.

**Comment by ddbeck** [comment]
> So I think it would be better all round to call all a normal property, and describe its behavior in the prose.

Oh yeah, this is obviously the right thing to do, now that I've accidentally made the reductio ad absurdum proposal. A regular property page could still have a constituent property section even, in `prose.*`.
