### ISSUE TITLE
Should we use front matter instead of meta.yaml?

### ISSUE THREAD

**Issue by wbamberg** [mdn/stumptown-content#69]
(meta: taken from https://github.com/mdn/stumptown-content/wiki/Notes-from-Whistler-All-Hands,-June-2019#front-matter-versus-metayaml-files)

In the HTML element docs we have prose.md for the content and meta.yaml for metadata, which includes `title` and `mdn_url` but also things like `browser_compatibility`.

In the guide pages we also have some metadata: at least `title` and `mdn_url`. We seem to lean here towards keeping them in the Markdown file as front matter:

```
---
title: Introduction to HTML
mdn_url: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML
---
At its heart, HTML is a fairly simple language...
```

This seems to be inconsistent. Should we use front matter for `title` and `mdn_url` even in reference docs? Should we keep all metadata in front matter, and abolish meta.yaml entirely?

We have had this conversation before, and decided to keep it in a separate file, for now. The argument for that being that lots of metadata at the start of a Markdown file makes it harder to read. But we should rethink this.

**Comment by wbamberg** [comment]
Especially given the stuff about guide pages above, I think I'm in favour of using front matter here. Having fewer files and keeping more stuff together is also a point in favour of front matter.

**Comment by peterbe** [comment]
I think the best argument I can think of is that it looks just fine in GitHub's preview thingy. 

<img width="1040" alt="Screen Shot 2019-07-11 at 4 03 54 PM" src="https://user-images.githubusercontent.com/26739/61081585-8c705d80-a3f5-11e9-93a7-57844b830277.png">

Also, if you're in a file called something super generic like `prose.md`, in your editor, the having the front-matter there would actually be super helpful. E.g.:

<img width="767" alt="Screen Shot 2019-07-11 at 4 05 07 PM" src="https://user-images.githubusercontent.com/26739/61081667-c477a080-a3f5-11e9-9e45-9b186a9e88e5.png">

**Comment by peterbe** [comment]
Less files ==> 👍
