### ISSUE TITLE
related_content's mdn_url is different from the main doc

### ISSUE THREAD

**Issue by peterbe** [mdn/stumptown-content#75]
Looking at `packaged/html/reference/elements/abbr.json` for example.

Looks like this:
```
{
   "related_content": [
    {
      "title": "Learn HTML",
      "content": [
        {
          "title": "Introduction to HTML",
          "content": [
            {
              "title": "Introduction to HTML",
              "mdn_url": "https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML"
            },
           ...

  "title": "<abbr>: The Abbreviation element",
  "mdn_url": "https://developer.mozilla.org/docs/Web/HTML/Element/abbr",
  "interactive_example_url": "https://interactive-examples.mdn.mozilla.net/pages/tabbed/abbr.html",
  "browser_compatibility": {
    ...
```

Note the difference in `mdn_url`values. Some are with `en-US` and some are not. 

We've talked before about at least dropping the absolute part with the domain. No doubt. But should we go for the locale prefix? My inclination is to NOT have the locale in there. Some day, the `abbr.json` file will be called something like `packaged/en-US/html/reference/elements/abbr.json` (or `packaged/sv-SE/html/reference/elements/abbr.json`) so that piece of information will be implicit. 

However, it could be that the lazy Swedes haven't translated every page yet so they might want to link to the en-US version in their side bars because it's better to point the English content than to not link at all. So for that reason it might be good to have the locale in there.

**Comment by peterbe** [comment]
By the way, the current Stumptown-renderer does NOT have locales in the URLs like MDN does. If we're ever going to have a chance to migrate, I think we should stick with the MDN-like URLs and start using en-US in stumptown-renderer for now. 

Based on that loud-thought I'm starting to think that the right thing to do is to always have the locale in the URIs. Always.

**Comment by peterbe** [comment]
I think we should start encoding the locale sooner rather than later in the renderer prototype.
See https://github.com/mdn/stumptown-renderer/issues/57

We can discuss the less useful "/docs/" URI segment some other day. :)

**Comment by wbamberg** [comment]
@peterbe , I think we can close this one now can't we?

**Comment by peterbe** [comment]
Yup. I grepped and the only full URLs I see are in the `__compat` block. E.g.
```
          "__compat": {
            "mdn_url": "https://developer.mozilla.org/docs/Web/HTML/Element/ins",
```
I don't we're using that in stumptown-renderer are we now that we have the `query`?
