### ISSUE TITLE
Rename markdown files?

### ISSUE THREAD

**Issue by ddbeck** [mdn/stumptown-content#93]
Right now, most of the markdown files have one name: `docs.md`. This makes it confusing to have multiple markdown files open in an editor at once. It'd be nice to have more descriptive names (for example, `html/reference/elements/abbr/abbr.md` instead of `html/reference/elements/abbr/docs.md`).

To be able to do this, we need to figure out the rules for deciding which files to build from. Previously, `meta.yml` file was the giveaway that a folder contained the files needed to build JSON. @wbamberg raised some possible solutions (and noted some drawbacks) in https://github.com/mdn/stumptown-content/pull/91#issuecomment-517350176; there may be others.

We ought to:

- [ ] Decide on a naming convention and a method for selecting files to build from
- [ ] Merge a PR that changes the build and renames the files

**Comment by ddbeck** [comment]
One half-baked idea I've had: can we use something in the front matter of a file as a way to identify the root markdown file of a page? For example, can we walk the directory tree looking for markdown files with a `recipe` front matter field as a way to identify buildable units of content?

**Comment by wbamberg** [comment]
I've been thinking about guide pages today, and I think we will need to fix this problem for guide pages, where you really want something like "/html/guides" containing a pile of sensibly-named MD files, one for each guide. 

> can we walk the directory tree looking for markdown files with a recipe front matter field as a way to identify buildable units of content?

This sounds promising and I will have a go at doing this for a first-version implementation of guide pages. But I do also like the last option [here](https://github.com/mdn/stumptown-content/pull/91#issuecomment-517350176), of driving the collection-of-pages step from an explicit listing, rather that scanning everything under./content.

**Comment by ddbeck** [comment]
Maybe we can combine strategies? For instance, we could use a manifest for guides and other loosely-structured content and use a scanning strategy for references. Or allow manifest files to collect whole directories with a wild card.

The reason I suggest this is that when I set a team up with Sphinx, the `toctree` directives were a big source of writer discontent. Some of the writers took to it immediately, others wouldn't stop telling me how much it frustrated them (they thought adding a file to a relevant directory was a sufficiently explicit declaration that they wanted to include that content in the output).

Alternatively, we can scan everything in `/content` as a linting strategy: if something is in `/content` but not in a manifest, then you get a warning or error. Sphinx can do this and it's OK, but it does lead to lots of annoyed "ugh update ToC" commits.

**Comment by wbamberg** [comment]
> The reason I suggest this is that when I set a team up with Sphinx, the toctree directives were a big source of writer discontent. Some of the writers took to it immediately, others wouldn't stop telling me how much it frustrated them (they thought adding a file to a relevant directory was a sufficiently explicit declaration that they wanted to include that content in the output).

That's interesting and good to know. But also the related_content thing enables you to say "include everything under this directory" so where that's appropriate, the writer doesn't have to update it when they add a new page. For example, given https://github.com/mdn/stumptown-content/blob/master/content/related_content/html.yaml, a writer only has to add a new page under /elements and it will show up in the build.

**Comment by ddbeck** [comment]
Cool! I think that will be good enough to avoid a writers' revolt.

**Comment by wbamberg** [comment]
I think https://github.com/mdn/stumptown-content/pull/167 fixes this issue, but please reopen if you disagree.
